# Generated by Django 5.0.2 on 2024-02-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=255)),
                ('icon', models.ImageField(upload_to='images/categories/images')),
                ('image', models.ImageField(upload_to='images/categories/icons')),
            ],
        ),
    ]
