# Generated by Django 5.0.2 on 2024-02-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='category_id',
        ),
    ]
